
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.1.32210.238
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MakeFile", "MakeFile\MakeFile.csproj", "{2DED8DB1-1E58-4EE0-B8A7-12AAF0773DF5}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{2DED8DB1-1E58-4EE0-B8A7-12AAF0773DF5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{2DED8DB1-1E58-4EE0-B8A7-12AAF0773DF5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{2DED8DB1-1E58-4EE0-B8A7-12AAF0773DF5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{2DED8DB1-1E58-4EE0-B8A7-12AAF0773DF5}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {6DAB4727-DCFB-461F-A760-F1E49B78B8D8}
	EndGlobalSection
EndGlobal
